// ignore_for_file: deprecated_member_use
part of floy;

class FloyAppBar {
  static AppBar copyWith({
    required AppBar appBar,
    Key? key,
    double? toolbarHeight,
    Widget? leading,
    bool? automaticallyImplyLeading,
    Widget? title,
    List<Widget>? actions,
    Widget? flexibleSpace,
    PreferredSizeWidget? bottom,
    double? elevation,
    double? scrolledUnderElevation,
    Color? shadowColor,
    Color? surfaceTintColor,
    ShapeBorder? shape,
    Color? backgroundColor,
    Color? foregroundColor,
    Brightness? brightness,
    IconThemeData? iconTheme,
    IconThemeData? actionsIconTheme,
    TextTheme? textTheme,
    bool? primary,
    bool? centerTitle,
    bool? excludeHeaderSemantics,
    double? titleSpacing,
    double? toolbarOpacity,
    double? bottomOpacity,
    double? leadingWidth,
    bool? backwardsCompatibility,
    TextStyle? toolbarTextStyle,
    TextStyle? titleTextStyle,
    SystemUiOverlayStyle? systemOverlayStyle,
    bool? forceElevated,
    double? expandedHeight,
    double? collapsedHeight,
    double? topPadding,
    bool? floating,
    bool? pinned,
  }) {
    return AppBar(
      key: key ?? appBar.key,
      toolbarHeight: toolbarHeight ?? appBar.toolbarHeight,
      leading: leading ?? appBar.leading,
      automaticallyImplyLeading: automaticallyImplyLeading ?? appBar.automaticallyImplyLeading,
      title: title ?? appBar.title,
      actions: actions ?? appBar.actions,
      flexibleSpace: flexibleSpace ?? appBar.flexibleSpace,
      bottom: bottom ?? appBar.bottom,
      elevation: elevation ?? appBar.elevation,
      scrolledUnderElevation: scrolledUnderElevation ?? appBar.scrolledUnderElevation,
      shadowColor: shadowColor ?? appBar.shadowColor,
      surfaceTintColor: surfaceTintColor ?? appBar.surfaceTintColor,
      shape: shape ?? appBar.shape,
      backgroundColor: backgroundColor ?? appBar.backgroundColor,
      foregroundColor: foregroundColor ?? appBar.foregroundColor,
      brightness: brightness ?? appBar.brightness,
      iconTheme: iconTheme ?? appBar.iconTheme,
      actionsIconTheme: actionsIconTheme ?? appBar.actionsIconTheme,
      textTheme: textTheme ?? appBar.textTheme,
      primary: primary ?? appBar.primary,
      centerTitle: centerTitle ?? appBar.centerTitle,
      excludeHeaderSemantics: excludeHeaderSemantics ?? appBar.excludeHeaderSemantics,
      titleSpacing: titleSpacing ?? appBar.titleSpacing,
      toolbarOpacity: toolbarOpacity ?? appBar.toolbarOpacity,
      bottomOpacity: bottomOpacity ?? appBar.bottomOpacity,
      leadingWidth: leadingWidth ?? appBar.leadingWidth,
      backwardsCompatibility: backwardsCompatibility ?? appBar.backwardsCompatibility,
      toolbarTextStyle: toolbarTextStyle ?? appBar.toolbarTextStyle,
      titleTextStyle: titleTextStyle ?? appBar.titleTextStyle,
      systemOverlayStyle: systemOverlayStyle ?? appBar.systemOverlayStyle,
    );
  }
}

class FloySliverAppBar {
  static SliverAppBar copyWith({
    required SliverAppBar sliverAppBar,
    Key? key,
    AsyncCallback? onStretchTrigger,
    bool? snap,
    bool? stretch,
    double? stretchTriggerOffset,
    Widget? leading,
    bool? automaticallyImplyLeading,
    Widget? title,
    List<Widget>? actions,
    Widget? flexibleSpace,
    PreferredSizeWidget? bottom,
    double? elevation,
    double? scrolledUnderElevation,
    Color? shadowColor,
    Color? surfaceTintColor,
    bool? forceElevated,
    Color? backgroundColor,
    Color? foregroundColor,
    Brightness? brightness,
    IconThemeData? iconTheme,
    IconThemeData? actionsIconTheme,
    TextTheme? textTheme,
    bool? primary,
    bool? centerTitle,
    bool? excludeHeaderSemantics,
    double? titleSpacing,
    double? expandedHeight,
    double? collapsedHeight,
    double? topPadding,
    bool? floating,
    bool? pinned,
    ShapeBorder? shape,
    double? toolbarHeight,
    double? leadingWidth,
    bool? backwardsCompatibility,
    TextStyle? toolbarTextStyle,
    TextStyle? titleTextStyle,
    SystemUiOverlayStyle? systemOverlayStyle,
  }) {
    return SliverAppBar(
      key: key ?? sliverAppBar.key,
      onStretchTrigger: onStretchTrigger ?? sliverAppBar.onStretchTrigger,
      snap: snap ?? sliverAppBar.snap,
      stretch: stretch ?? sliverAppBar.stretch,
      stretchTriggerOffset: stretchTriggerOffset ?? sliverAppBar.stretchTriggerOffset,
      leading: leading ?? sliverAppBar.leading,
      automaticallyImplyLeading:
          automaticallyImplyLeading ?? sliverAppBar.automaticallyImplyLeading,
      title: title ?? sliverAppBar.title,
      actions: actions ?? sliverAppBar.actions,
      flexibleSpace: flexibleSpace ?? sliverAppBar.flexibleSpace,
      bottom: bottom ?? sliverAppBar.bottom,
      elevation: elevation ?? sliverAppBar.elevation,
      scrolledUnderElevation: scrolledUnderElevation ?? sliverAppBar.scrolledUnderElevation,
      shadowColor: shadowColor ?? sliverAppBar.shadowColor,
      surfaceTintColor: surfaceTintColor ?? sliverAppBar.surfaceTintColor,
      forceElevated: forceElevated ?? sliverAppBar.forceElevated,
      backgroundColor: backgroundColor ?? sliverAppBar.backgroundColor,
      foregroundColor: foregroundColor ?? sliverAppBar.foregroundColor,
      brightness: brightness ?? sliverAppBar.brightness,
      iconTheme: iconTheme ?? sliverAppBar.iconTheme,
      actionsIconTheme: actionsIconTheme ?? sliverAppBar.actionsIconTheme,
      textTheme: textTheme ?? sliverAppBar.textTheme,
      primary: primary ?? sliverAppBar.primary,
      centerTitle: centerTitle ?? sliverAppBar.centerTitle,
      excludeHeaderSemantics: excludeHeaderSemantics ?? sliverAppBar.excludeHeaderSemantics,
      titleSpacing: titleSpacing ?? sliverAppBar.titleSpacing,
      expandedHeight: expandedHeight ?? sliverAppBar.expandedHeight,
      collapsedHeight: collapsedHeight ?? sliverAppBar.collapsedHeight,
      floating: floating ?? sliverAppBar.floating,
      pinned: pinned ?? sliverAppBar.pinned,
      shape: shape ?? sliverAppBar.shape,
      toolbarHeight: toolbarHeight ?? sliverAppBar.toolbarHeight,
      leadingWidth: leadingWidth ?? sliverAppBar.leadingWidth,
      backwardsCompatibility: backwardsCompatibility ?? sliverAppBar.backwardsCompatibility,
      toolbarTextStyle: toolbarTextStyle ?? sliverAppBar.toolbarTextStyle,
      titleTextStyle: titleTextStyle ?? sliverAppBar.titleTextStyle,
      systemOverlayStyle: systemOverlayStyle ?? sliverAppBar.systemOverlayStyle,
    );
  }
}
